
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-3
pull_requests: [{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-Location","number":27,"title":"Add Location Service and Test","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-3/pull/27"},{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ZipCode","number":26,"title":"Add Zip Codes Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-3/pull/26"},{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"Kate-PublicHolidayController","number":24,"title":"Add Public Holiday Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-3/pull/24"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-University-Controller","number":21,"title":"updated UniversityController and completed test cases","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-3/pull/21"}]
