
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-HomeController","number":33,"title":"Add Home Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-3/pull/33"},{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ZipCodeController","number":32,"title":"Add Zip Code Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-3/pull/32"}]
